image:
  file: .gitpod.Dockerfile
tasks:
  - name: aws-cli
    env:
      AWS_CLI_AUTO_PROMPT: on-partial
    before: |
      chmod +x aws-cli-login.sh

vscode:
  extensions:
    - hashicorp.terraform      
      